import { bool, cleanEnv, num, port, str } from 'envalid'

export const Env = cleanEnv(process.env, {
    NODE_ENV: str(),
    SERVICE_NAME: str(),
    PORT: port(),
    TIMEZONE: str(),
    LOG_FORMAT: str(),
    LOG_DIR: str(),
    ORIGIN: str(),
    CREDENTIALS: bool(),
    DB_HOST: str(),
    DB_PORT: num(),
    DB_USER: str(),
    DB_PASSWORD: str(),
    DB_DATABASE: str(),
    MAIL_HOST: str(),
    MAIL_PORT: num(),
    MAIL_USER: str(),
    MAIL_PASSWORD: str(),
    MAIL_RECEIVER: str(),
    SMS019_API_HOST: str(),
    SMS019_API_SANDBOX_HOST: str(),
    SMS019_API_USERNAME: str(),
    SMS019_API_PASSWORD: str(),
    REQUEST_TIMEOUT: num(),
    REQUEST_SCHEDULER_CRON: str(),
    REQUEST_MAX_ATTEMPTS_ON_TIMEOUT: num(),
})
